[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path = 'forge-cache'
gas_reports = ["ChainWarzLottery", "BlackListManager", "MockChainWarzLottery"]
optimizer = true
optimizer_runs = 20000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config